import type { Metadata } from "next";
import { Alata } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import Footer from "@/app/_components/footer";
import Header from "./_components/header";

const alata = Alata({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={alata.className}>
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
